### ISSUE TITLE
 iPhoneX対応

### ISSUE THREAD

**Issue by Lee-junha** [dolfalf/Hakenman#2]
- [x] Tutorial
- [x] Information
- [x] Top
- [x] Setting
- [x] Menu

**Comment by dolfalf** [comment]
튜토리얼 레이아웃 조정완료.

**Comment by cds2363** [comment]
Top画面レイアウト調整完了。

**Comment by toshimaPower** [comment]
@dolfalf 
Information은 어떻게 하면 표시할수 있는거에요?

**Comment by dolfalf** [comment]
성기랑 작업해서 화면 다 끝냄
