### ISSUE TITLE
不具合一覧

### ISSUE THREAD

**Issue by vkdlxh** [dolfalf/Hakenman#37]
- 設定→プライバシーポリシーをタップすると落ちる
確認端末 : テヒョンさんのiPhone 7
（iPhone xs 13.5は落ちない）
-> 韓国語の場合落ちることを確認

- 過去のデータを作成するとすぐに反映されない

- ダークモードの場合、当月のチャートの値の文字色が黒なので見えない

- #30 以前合宿で確認された件ですが、もう一回確認お願いします。

**Comment by dolfalf** [comment]
#30 についてはコメントしました。

**Comment by dolfalf** [comment]
分けてissueを作ったのでクローズします。
