### ISSUE TITLE
Swift対応

### ISSUE THREAD

**Issue by Lee-junha** [dolfalf/Hakenman#4]
- [ ] Tutorial
- [ ] Information
- [ ] Top
- [ ] Setting
- [ ] Menu

**Comment by toshimaPower** [comment]
@Lee-junha @dolfalf 
여기는 그냥 파일만 넣어서는 준비해두는거 아니였어요?

**Comment by dolfalf** [comment]
일단 머지 했으니 된거니 클로즈 한다앙~
